language: minimal
matrix:
  include:
  - env: GHCVER=8.2
  - env: GHCVER=8.4
  - env: GHCVER=8.6
  - env: GHCVER=8.8
  - env: GHCVER=8.10
  - env: GHCVER=head

script:
- git clone https://github.com/jacereda/fsatrace.git .fsatrace
- (cd .fsatrace && make)
- export PATH=$PATH:`pwd`/.fsatrace
- fsatrace v - -- echo fsatrace works
- curl -sSL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
